# Generated by Django 5.1.2 on 2024-11-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_19_3', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Intermediate', max_length=100),
            preserve_default=False,
        ),
    ]
